# Site settings
title:              Portfolio
email:              andrewthompson2019@u.northwestern.edu
description:        "Portfolio for Andrew Thompson at Northwestern University"
url:                "http://localhost:4000"
baseurl:            /msr-awt-portfolio

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
